"""One-page PDF export of a deal report, built with fpdf2."""
from __future__ import annotations

from fpdf import FPDF

from reports.report_builder import ReportData

DISCLAIMER = (
    "Decision support only. Not legal, tax, or financial advice. Verify every number with a "
    "lender, attorney, and inspector before buying. Generated by RE-VA; never sent or acted on automatically."
)


_ASCII_REPLACEMENTS = {
    "—": "-",  # em dash
    "–": "-",  # en dash
    "‘": "'",
    "’": "'",
    "“": '"',
    "”": '"',
}


def _sanitize(text: str) -> str:
    """The core Helvetica font only supports latin-1; swap common smart
    punctuation for plain ASCII rather than requiring a Unicode font file."""
    for char, replacement in _ASCII_REPLACEMENTS.items():
        text = text.replace(char, replacement)
    return text


def _line(pdf: FPDF, h: float, text: str) -> None:
    """multi_cell(w=0) measures from the CURRENT x, not the left margin, so we
    reset x first or a long first line leaves no room for the next one."""
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, h, _sanitize(text))


def build_pdf(report: ReportData, explanation: str | None = None) -> bytes:
    pdf = FPDF(format="Letter")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    _line(pdf, 8, report.deal_name)
    pdf.set_font("Helvetica", "", 11)
    _line(pdf, 6, report.address)
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 13)
    target = f" (target price ${report.verdict_target_price:,.0f})" if report.verdict_target_price else ""
    _line(pdf, 7, f"Verdict: {report.verdict_outcome}{target}")
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 12)
    _line(pdf, 7, "Key metrics")
    pdf.set_font("Helvetica", "", 10)
    for k, v in report.key_metrics.items():
        _line(pdf, 5.5, f"  {k}: {v}")
    pdf.ln(2)

    def _bullet_section(title: str, items: list[str]) -> None:
        pdf.set_font("Helvetica", "B", 12)
        _line(pdf, 7, title)
        pdf.set_font("Helvetica", "", 10)
        for item in items:
            _line(pdf, 5.5, f"  - {item}")
        pdf.ln(1)

    _bullet_section("Top risks", report.risks)
    _bullet_section("Top strengths", report.strengths)
    _bullet_section("Questions to ask the broker/seller", report.questions)

    if explanation:
        pdf.set_font("Helvetica", "B", 12)
        _line(pdf, 7, "In plain English")
        pdf.set_font("Helvetica", "", 10)
        _line(pdf, 5.5, explanation)
        pdf.ln(1)

    pdf.set_font("Helvetica", "I", 8)
    _line(pdf, 4.5, DISCLAIMER)

    return bytes(pdf.output())
